# Generated by Django 4.1.7 on 2023-03-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("navmenu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="menu_name",
            field=models.CharField(default="main", max_length=100),
        ),
    ]
